@mainHost = http://92.38.48.35:5000/api/v1/
@host = http://92.38.48.35:5003/api/v1/
### health
GET {{host}}health

### Get JWT access token by password and user login
# @name loginReq
POST {{mainHost}}authenticate
Content-Type: application/json

{
    "username":"admin",
    "password":"q1234567q"
}

### Get the list of Order, using advanced search
POST {{host}}orders/search
Authorization: Bearer {{loginReq.response.body.token}}
Content-Type: application/json

{
    "paging": {
        "skip": 0,
        "take": 10,
        "returnCount": true
    },
    "sort": {
        "id": {
            "operator": "asc",
            "ordinal": 0,
        },
    },
}

### Add an Order (Undefined -> Created via workflow)
POST {{host}}orders
Authorization: Bearer {{loginReq.response.body.token}}
Content-Type: application/json

{
    "clientId": 1,
    "channelId": 3,
}

### Run order workflow transition
POST {{host}}orders/workflow/run
Authorization: Bearer {{loginReq.response.body.token}}
Content-Type: application/json

{
    "id": 1,
    "previousState": 1,
    "nextState": 2,
}

### Edit a Order
PUT {{host}}orders
Authorization: Bearer {{loginReq.response.body.token}}
Content-Type: application/json

{
    "id": 1,
    "state": 1,
    "clientId": 1,
    "channelId": 1,
}

### Delete a Order
DELETE {{host}}orders/1
Authorization: Bearer {{loginReq.response.body.token}}
Content-Type: application/json

{
}

